"""Constants for ESP32 Casambi."""
DOMAIN = "esp32_casambi"
CONF_HOST = "host"
CONF_PASSWORD = "password"
DEFAULT_PORT = 80
DEFAULT_SCAN_INTERVAL = 10
API_TOKEN_PREFIX = "casambi-api:"
API_KEY_HEADER = "X-API-Key"
CASAMBI_MAX_LEVEL = 255
CASAMBI_OFF_LEVEL_THRESHOLD = 1
PLATFORMS = ["light", "scene"]
